# Generated by Django 4.1.7 on 2023-03-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Url',
            new_name='RandomUrl',
        ),
        migrations.RenameField(
            model_name='randomurl',
            old_name='ulr_name',
            new_name='random_url_name',
        ),
    ]
